name: Context Demo
on: push
jobs:
  context_demo:
    runs-on: ubuntu-latest
    steps:
      - name: use context variables
        run: |
          echo "THis is triggered by ${{ github.actor }}"
          echo " Repository name ${{ github.repository }}" 
      - name: print all variables under github
        run: echo "${{ toJson(github) }}"
          
