name: Workflow triggers
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
jobs:
  build_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow triggers
        run: echo "Workflow Triggers"
      - name: Repository Variables
        run: echo "Hello, ${{ vars.NAME }}"
      - name: Repository secrets
        run: echo "Password is ${{ secrets.PASSWORD }}"
  
